# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeIt' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PracticeIt
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'UITextField+Shake', '~> 1.1'
  pod 'MZFormSheetPresentationController', '~> 2.4'
  use_frameworks!
  pod "TableViewDragger"

  target 'PracticeItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PracticeItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
